### PR TITLE
Bad cached BMP: gdi32.GetDIBits() failed

### PR DESCRIPTION
**Pull request by CTPaHHuK-HEbA**
For fast grab i use 2 grab: one grab only box(const), other grab line(const).
Fast - not calls: create_string_buffer + gdi32.DeleteObject + gdi32.CreateCompatibleBitmap + gdi32.SelectObject 
+ Bad idea after failed

Found Bug:
```python
from mss import mss

grab1 = mss()
grab2 = mss()
print(id(grab1) == id(grab2))

grab1.grab({'top': 0, 'left': 0, 'width': 100, 'height': 100})
grab2.grab({'top': 0, 'left': 0, 'width': 50, 'height': 1})
grab1.grab({'top': 0, 'left': 0, 'width': 100, 'height': 100})
```

```python
  File "C:\Program Files\Python310\lib\site-packages\mss\windows.py", line 285, in _grab_impl
    raise ScreenShotError("gdi32.GetDIBits() failed.")
mss.exception.ScreenShotError: gdi32.GetDIBits() failed.
```

### CODE REVIEW

**Comment by CTPaHHuK-HEbA** [comment]
This patch solves the problem when multiple grabers are used, but does not solve the problem of multithreading :(
This global problem, when used cached MSS.bmp and MSS.memdc

If run code - all ok
```
from multiprocessing.pool import ThreadPool
import threading
import mss

Thread = 4

def grab_pr(bbox):
    with mss.mss() as sct:
        for i in range(50):
            # bbox = sct.monitors[0]  # FAIL 
            print(bbox, sct, threading.main_thread(), threading.current_thread())
            im = sct.grab(bbox)

if __name__ == '__main__':
    print(threading.main_thread(), threading.current_thread())
    arg = [(10, 10, 1000 + i, 1000 + i) for i in range(Thread )]
    pool = ThreadPool(Thread)
    results = pool.map(grab_pr, arg)
    pool.close()
    pool.join()

```
But uncoment line: # bbox = sct.monitors[0]  # FAIL 
Return error:
mss.exception.ScreenShotError: gdi32.GetDIBits() failed

**Comment by CTPaHHuK-HEbA** [comment]
It is necessary that each thread uses only its own cache: bmp and memdc. Well, if there is no multithreading, then one is enough for everyone.

**Comment by CTPaHHuK-HEbA** [comment]
If use patch windows.py from #212 - all Thred ok!

**Comment by CTPaHHuK-HEbA** [comment]
New commit fix  and  thread. 

Description bug:
Grab1 or Thread1  region (x, y, h, w)  
Set MSS.bmp = CreateCompatibleBitmap(srcdc, w, h)

Grab2 or Thread2  region (x2, y2, h2, w2)
Change MSS.bmp = CreateCompatibleBitmap(srcdc, w2, h2)

Grab1 or Thread1  region (x, y, h, w)  
He thinks MSS.bmp == CreateCompatibleBitmap(srcdc, **w, h**) and not change.
But MSS.bmp == CreateCompatibleBitmap(srcdc, **w2, h2**)
BUG

**Comment by BoboTiG** [comment]
I just updated the `master` branch with a complete CI running on GitHub Actions. Would you mind rebasing your pull request?

**Comment by BoboTiG** [comment]
The CI is green again on the `master` branch. It will help here :)

**Comment by BoboTiG** [comment]
I'll review how those attributes are stored, because that's quite a mess what I did haha

**Comment by BoboTiG** [comment]
Thanks @CTPaHHuK-HEbA, sorry for the loooong delay. I incorporated your tests in #250, and they all pass (even if some are not really relevant, I kept all of them for safety).

**Pull request closed without merging**
