### PR TITLE
Linux: Mouse support

### PR DESCRIPTION
**Pull request by zorvios**
### Changes proposed in this PR

- Partial Fix for #55 
-- Linux cursor image
-- merge the cursor into the pixels directly and not only in the final PNG
-- Added keyword  with_cursor=False

It is **very** important to keep up to date tests and documentation.

- [ ] Tests added/updated
- [ ] Documentation updated

Is your code right?

- [x] PEP8 compliant
- [x] `flake8` passed

### CODE REVIEW

**Comment by BoboTiG** [comment]
Hello @zorvios,

Sorry for all those code changes since your opened the PR, and a big thank you for your work 💪 

I will come back to you later, I need to think about how that new feature could be implemented.

**Comment by AwesomeDude091** [comment]
Is this ever going to ship?

**Comment by AwesomeDude091** [comment]
> Is this ever going to ship?

????

**Comment by AwesomeDude091** [comment]
Yay it got approved, now let's merge it and be done with it :)

**Pull request closed without merging**
