### PR TITLE
Ignore missing SetProcessDPIAware on WinXP

### LINKED ISSUE #109: MSS.__init__ throws AttributeError due to SetProcessDPIAware on XP
General information:

* OS name: _Windows_
* OS version: __XP 5.1.2600__
* OS architecture: _32 bits_
* Resolutions:
    * Monitor 1: _1920x975_
* Python version: _2.7.13_
* MSS version: __4.0.1__

### Description of the warning/error

MSS.\_\_init\_\_ fails to initialize on XP because when SetProcessDpiAwareness fails, it falls back to SetProcessDPIAware, which was added in Vista. Wrapping it in another try/except for the Attribute error makes it work fine. (I tried to make a pull request but ran into issues with github's UI and gave up, but it's a minor fix)

### Full message

```
Traceback (most recent call last):
  File "sc2k.py", line 58, in <module>
    take_screenshot(filename)
  File "sc2k.py", line 30, in take_screenshot
    with mss.mss() as sct:
  File "C:\Python27\lib\site-packages\mss\factory.py", line 38, in mss
    return MSS(**kwargs)
  File "C:\Python27\lib\site-packages\mss\windows.py", line 92, in __init__
    self.user32.SetProcessDPIAware()
  File "C:\Python27\lib\ctypes\__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'SetProcessDPIAware' not found
```

### PR DESCRIPTION
**Pull request by foone**
### Changes proposed in this PR

- Fixes #109

Is your code right?

- [✓] PEP8 compliant
- [✓] `flake8` passed

### CODE REVIEW

**Comment by BoboTiG** [comment]
Thanks!
Could you have  a look at the CI?

**Comment by BoboTiG** [comment]
And perhaps could you add ypuself to contributors if you want.

**Comment by foone** [comment]
Sorry, fixed the CI issue. No need for contributor credit for such a minor thing.

**Comment by BoboTiG** [comment]
Thanks @foone :)

**Pull request merged**
